#ifndef INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_EVENT_HPP_
#define INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_EVENT_HPP_

namespace asc {
	struct EntityEvent {

	};
}

#endif // INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_EVENT_HPP_