#ifndef INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_RESOURCE_HPP_
#define INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_RESOURCE_HPP_

namespace asc {
	class EntityResource {
	public:
		EntityResource(void);
		~EntityResource(void);
	};
}

#endif // INCLUDED_ASCENDANCY_ENTITY_FRAMEWORK_ENTITY_RESOURCE_HPP_